# Generated by Django 6.0.2 on 2026-02-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='not_like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_like',
            field=models.IntegerField(default=0),
        ),
    ]
