# Generated by Django 6.0.2 on 2026-02-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comment_is_like_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogg',
        ),
    ]
